
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: healthcheck

feign:
  client:
    config:
      default:
        loggerLevel: FULL

open-critic-client:
  name: openCriticApi
  url: https://api.opencritic.com/api